Inventory/Inventory/Models/Breed.cs
namespace Inventory.Models
{
    public class Breed
    {


        public int Id { get; set; }

        public string BreedName { get; set; }=string.Empty;

        public string ImgUrl { get; set; }=string.Empty;

        public int Parent1BreedId { get; set; }
        public int Parent2BreedId { get; set; }


        public Breed()
        {
        }
        //public Breed(string newBreed)
        //{
        //   BreedName = newBreed;
        // }

    }




}

Inventory/Inventory/Models/Breeds.cs
using Inventory.Services;
using System;
using System.Collections.Generic;

namespace Inventory.Models
{
    public class Breeds
    {
        public List<Breed> allBreeds = new List<Breed>();

        public Breeds()
        {
            allBreeds = Database.GetAllBreeds();
        }

    }
}

Inventory/Inventory/Models/Dog.cs
using System.ComponentModel.DataAnnotations;
namespace Inventory.Models
{
    public class Dog
    {
        public int ID { get; set; }

        public string Name { get; set; } = string.Empty;

        public int BreedID { get; set; }
        public int MotherID { get; set; }
        public int FatherID { get; set; }
        public int KennelID { get; set; }
        public string Pedigree { get; set; } = string.Empty;
        public string Sex { get; set; } = string.Empty;
    }
}

Inventory/Inventory/Models/Dogs.cs
using Inventory.Services;
using System;
using System.Collections.Generic;

namespace Inventory.Models
{
    public class Dogs
    {
        public List<Dog> allDogs = new List<Dog>();


        public Dogs()
        {
            allDogs = Database.GetAllDogs();

        }

        public Dog selectdog=new Dog();

        public Dogs(int id)
        {
            selectdog = Database.SelectDog(id);
        }

        public void Delete(int dogid)
        {
            Database.DeleteDog(dogid);
        }

        public void Edit(int dogid, string name, int kennelid)
        {
            Database.EditDog(dogid, name, kennelid);
        }

        public void Add(string name, int breedid, int motherid, int fatherid, int kennelid, string pedigree,string sex)
        {
            Database.AddDog(name, breedid, motherid, fatherid, kennelid, pedigree,sex);
        }


    }
}

Inventory/Inventory/Pages/Dogs/BOne.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class BOneModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public BOneModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/BThree.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class BThreeModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public BThreeModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/BTwo.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class BTwoModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public BTwoModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/Breed.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;


using Microsoft.EntityFrameworkCore;



namespace Inventory.Pages.Dogs
{
    public class BreedModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public BreedModel(Inventory.Data.InventoryContext context)
        {
            _context = context;


        }

        public IList<Breed> Breeds { get; set; }
        public IList<Dog> Dogs { get;set; }



        public IActionResult OnGet(string id, string parent1, string parent2)
        {
            //Breeds= new List<Breed>();
            Breeds = new Models.Breeds().allBreeds;
            Dogs = new Models.Dogs().allDogs;
            //int breed = newdogbreed;
            ViewData["breed"] = id;
            ViewData["Parent1"] = parent1;
            ViewData["Parent2"]= parent2;
            return  Page();
        }

        [BindProperty]
        public Dog Dog { get; set; }



        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public RedirectToPageResult OnPostBreed(string name, int breedid, int motherid, int fatherid, int kennelid, string pedigree, string sex, int licensenum, string username, string usersurname)
        {
            var usercheck = Database.VerifyUser(licensenum, username, usersurname);

            if(usercheck)
            {
                Database.AddDog(name, breedid, motherid, fatherid, kennelid, pedigree,sex);
            }
            else
            {
                return RedirectToPage("./Index");
            };
            

            return RedirectToPage("./Index");


        }

    }


}

Inventory/Inventory/Pages/Dogs/Breeding.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class BreedingModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public BreedingModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/Create.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class CreateModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public CreateModel(Inventory.Data.InventoryContext context)
        {
            _context = context;


        }

        public IList<Dog> Dogs { get; set; }
        public IList<Breed> Breeds { get; set; }


        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;



        }

        [BindProperty]
        public Dog Dog { get; set; }

        public RedirectToPageResult OnPostAdopt(string name, int breedid, int motherid, int fatherid, int kennelid, string pedigree, string sex)
        {
            
            Database.AddDog(name, breedid, motherid, fatherid, kennelid, pedigree,sex);

            return RedirectToPage("./Index");


        }

    }


}

Inventory/Inventory/Pages/Dogs/Delete.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class DeleteModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public DeleteModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Dog Dog { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {

            Dog = new Models.Dogs(id).selectdog;

            if (Dog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            Database.DeleteDog(id);

            return RedirectToPage("./Index");
        }
    }
}

Inventory/Inventory/Pages/Dogs/Details.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;

namespace Inventory.Pages.Dogs
{
    public class DetailsModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public DetailsModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }

        public Dog Dog { get; set; }

        

        public async Task<IActionResult> OnGetAsync(int id)
        {


            Dog = new Models.Dogs(id).selectdog;

            if (Dog == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Inventory/Inventory/Pages/Dogs/Edit.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class EditModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public EditModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public Dog Dog { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {


            Dog = new Models.Dogs(id).selectdog;

            if (Dog == null)
            {
                return NotFound();
            }
            return Page();
        }

            public RedirectToPageResult OnPostEdit(int id, string dogname, int kennel)
        {
            
            Database.EditDog(id, dogname, kennel);

            return RedirectToPage("./Index");
        }


    }
}

Inventory/Inventory/Pages/Dogs/Index.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class IndexModel : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public IndexModel(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;
            

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/KOne.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class KOne : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public KOne(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }


        public IList<Dog> Dog { get;set; }
        public IList<Breed> Breeds{ get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;
            

            Dog = new Models.Dogs().allDogs;

            
            
        }
        
    }
}

Inventory/Inventory/Pages/Dogs/KThree.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class KThree : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public KThree(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }



        public IList<Dog> Dog { get; set; }
        public IList<Breed> Breeds { get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;


            Dog = new Models.Dogs().allDogs;



        }
    }
}

Inventory/Inventory/Pages/Dogs/KTwo.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Inventory.Data;
using Inventory.Models;
using Inventory.Services;

namespace Inventory.Pages.Dogs
{
    public class KTwo : PageModel
    {
        private readonly Inventory.Data.InventoryContext _context;

        public KTwo(Inventory.Data.InventoryContext context)
        {
            _context = context;
        }




        public IList<Dog> Dog { get; set; }
        public IList<Breed> Breeds { get; set; }

        public async Task OnGetAsync()
        {

            Breeds = new Models.Breeds().allBreeds;


            Dog = new Models.Dogs().allDogs;



        }

    }
}

Inventory/Inventory/Pages/Dogs/Breed.cshtml
@page
@model Inventory.Pages.Dogs.BreedModel

@{
    ViewData["Title"] = "Breed";

    //var breeds = ViewData["Breeds"] as Array;
    var breed= ViewData["breed"] as string;
    var parent1 = ViewData["Parent1"] as string;
    var parent2 = ViewData["Parent2"] as string;

    var breedname = "";
    var breedimg = "";

    var mombreed="";
    var mompedigree="";

    var dadbreed="";
    var dadpedigree="";


}



<div class="row">
    <div class="row col-12">
        <div class="col-2"></div>

        <div class="row col-8">

            <h1 style="margin-top:2vh">New Puppy</h1>
            <form method="post" class="adopt_form row col-12" asp-page-handler="breed">

            <div class="row col-4">
                    @foreach (var dogbreed in Model.Breeds)
                {
                    if(breed == dogbreed.Id.ToString())
                        {
                        breedname = dogbreed.BreedName;
                        breedimg = dogbreed.ImgUrl;

                        

                        <div class="col-12 form-group">
                        <label style="font-size:larger" for="breedid" class="control-label">Breed: @dogbreed.BreedName</label>
                        <input type=hidden  name="breedid" class="form-control" value=@dogbreed.Id>
                        </div>
                        <img class="col-12 dog_img_create" src=@breedimg> 
                        
                        }
                    }



            </div>
            <div class="row col-8">
                <div class="col-6">
                
                    @foreach (var dog in Model.Dogs)
                    {
                        if(dog.ID.ToString() == parent1)
                        {
                        var dadname = dog.Name;
                        dadbreed=dog.BreedID.ToString();
                        dadpedigree=dog.Pedigree;

                <div class="form-group">
                    <label for="motherid" class="control-label">Father: @dog.Name</label>
                    <input  name="motherid" class="form-control" value=@dog.ID type="hidden"/>
                </div>

                        }
                    }

                    @foreach (var dog in Model.Dogs)
                    {
                        if(dog.ID.ToString() == parent2)
                        {
                        var momname = dog.Name;
                        mombreed=dog.BreedID.ToString();
                        mompedigree=dog.Pedigree;

                <div class="form-group">
                    <label for="fatherid" class="control-label">Mother: @dog.Name</label>
                    <input  name="fatherid" class="form-control" value=@dog.ID type="hidden"/>
                </div>

                        }
                    }
                        <div class="form-group">
                        @if (mombreed == dadbreed)
                        {
                        <label for="pedigree" class="control-label">Pedigree: Purebred</label>
                        <input value="Purebred" name="pedigree" class="form-control" type="hidden"/>
                        }
                        @if(mombreed != dadbreed)
                        {
                            if (mompedigree==dadpedigree)
                            {
                                if (mompedigree == "Purebred")
                                {
                        <label for="pedigree" class="control-label">Pedigree: f1</label>
                        <input value="f1" name="pedigree" class="form-control" type="hidden"/>
                                }
                                if (mompedigree == "f1")
                                {
                        <label for="pedigree" class="control-label">Pedigree: f2</label>
                        <input value="f2" name="pedigree" class="form-control" type="hidden"/>
                                }
                                if (mompedigree == "f2")
                                {
                        <label for="pedigree" class="control-label">Pedigree: f3</label>
                        <input value="f3" name="pedigree" class="form-control" type="hidden"/>
                                }
                                if (mompedigree == "f3")
                                {
                        <label for="pedigree" class="control-label">Pedigree: Multi Generation</label>
                        <input value="Multi Generation" name="pedigree" class="form-control" type="hidden"/>
                                }
                                if (mompedigree == "Multi Generation")
                                {
                        <label for="pedigree" class="control-label">Pedigree: Multi Generation</label>
                                        <input value="Multi Generation" name="pedigree" class="form-control" type="hidden"/>
                                    }
                                }
                                if (mompedigree != dadpedigree)
                                {
                                    if ((mompedigree == "Purebred") || (dadpedigree == "Purebred"))
                                    {
                        <label for="pedigree" class="control-label">Pedigree: Backbred</label>
                        <input value="Backbred" name="pedigree" class="form-control" type="hidden"/>
                                    }
                                    else
                                    {
                        <label for="pedigree" class="control-label">Pedigree: Multi Generation</label>
                        <input value="Multi Generation" name="pedigree" class="form-control" type="hidden"/>
                                    }

                            }
                        }

                </div>
                </div>
                <div class="col-6">
                <div class="form-group">
                    <label for="name" class="control-label">Name</label>
                    <input  name="name" class="form-control" type="text"/>
                </div>
                   
                <div class="form-group">
                    <label for="kennelid" class="control-label">Kennel: </label>
                    <select name="kennelid" class="form-control">
                        <option value="1">Kennel One</option>
                        <option value="2">Kennel Two</option>
                        <option value="3">Kennel Three</option>
                    </select> 
                </div>
 
                <div class="form-group">
                    <label for="sex" class="control-label">Sex:</label>
                    <select name="sex" class="form-control">
                        <option value="female">Female</option>
                        <option value="male">Male</option>
                    </select> 
                </div>
                </div>
                <p style="color:red;font-weight:lighter;font-size:smaller">Genetics can be very complicated and careless breeding can often have unforseen results. Thus we believe that this responsibility should be restricted to qualified breeders only.</p>
            </div>

            <div class="col-12">
                
                <div class="form-group">
                    <label style="color:black" for="username" class="control-label">Breeder Name</label>
                    <input  name="username" class="form-control" type="text"/>
                </div>

                <div class="form-group">
                    <label style="color:black" for="usersurname" class="control-label">Breeder Surname</label>
                    <input  name="usersurname" class="form-control" type="text"/>
                </div>
                <div class="form-group">
                    <label style="color:black" for="licensenum" class="control-label">License Number</label>
                    <input  name="licensenum" class="form-control" type="text"/>
                </div>
                <div class="form-group">
                    <input type="submit" value="Breed" class="btn btn-primary" style="background-color:#006DAA; float:right"/>
                </div>
            </div>


        </form>
        </div>

        <div class="col-2"></div>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inventory/Inventory/Pages/Dogs/Create.cshtml
@page
@model Inventory.Pages.Dogs.CreateModel

@{
    ViewData["Title"] = "Create";

    //var breeds = ViewData["Breeds ] as Array;


}



<div class="row">
    <div class="row col-12">
        <div class="col-3"></div>

        <div class="row col-6">
            <h1 style="margin-top:5vh">Adopt a Dog</h1>
            <form method="post" asp-page-handler="adopt" class="adopt_form row col-12">

            <div class="col-6">
                <div class="form-group">
                    <label for="breedid" class="control-label">Breed</label>
                    <select name="breedid" class="form-control">
                        <option value=0>---</option>
                        @foreach (var breed in Model.Breeds)
                        {
                                if (breed.Parent1BreedId == breed.Parent2BreedId)
                                {
                                    <option value=@breed.Id>@breed.BreedName</option>
                                }
                                
                        }
                    </select> 
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="name" class="control-label">Name</label>
                    <input name="name" class="form-control" type="text"/>
                </div>

                <div class="form-group">
                    <input name="motherid" type="hidden" value=0 class="form-control" />
                </div>

                <div class="form-group">
                    <input name="fatherid" type="hidden" value=0 class="form-control" />
                </div>
                <div class="form-group">
                    <label for="kennelid" class="control-label">Kennel: </label>
                    <select name="kennelid" class="form-control">
                        <option value="1">Kennel One</option>
                        <option value="2">Kennel Two</option>
                        <option value="3">Kennel Three</option>
                    </select> 
                </div>
                <div class="form-group">
                    <label for="pedigree" class="control-label">Pedigree: Purebred</label>
                    <input name="pedigree" type="hidden" value="Purebred" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="sex" class="control-label">Sex:</label>
                    <select name="sex" class="form-control">
                        <option value="female">Female</option>
                        <option value="male">Male</option>
                    </select> 
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Adopt" class="btn btn-primary" style="background-color:#006DAA;"/>
            </div>
        </form>
        </div>

        <div class="col-3"></div>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inventory/Inventory/Pages/Dogs/Delete.cshtml
@page
@model Inventory.Pages.Dogs.DeleteModel

@{
    ViewData["Title"] = "Delete";
}



<h3 style="margin-top:5%; margin-bottom:5%">Are you sure you want to Send @Html.DisplayFor(model => model.Dog.Name) Away?</h3>
<div>
    <hr />
    <dl class="row" style="margin-bottom:5%">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.BreedID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.BreedID)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.KennelID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.KennelID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.Pedigree)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.Pedigree)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Dog.ID" />
        <input type="submit" value="Send to Farm" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Inventory/Inventory/Pages/Dogs/Details.cshtml
@page
@model Inventory.Pages.Dogs.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Dog.Name)</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.BreedID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.BreedID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.MotherID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.MotherID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.FatherID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.FatherID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.KennelID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.KennelID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dog.Pedigree)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dog.Pedigree)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Dog.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Inventory/Inventory/Pages/Dogs/Edit.cshtml
@page
@model Inventory.Pages.Dogs.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="edit">
            <input name="id" class="form-control" type="hidden" value=@Model.Dog.ID />
            <div class="form-group">
                <label for="Name" class="control-label">Name</label>
                <input name="dogname" class="form-control" placeholder=@Model.Dog.Name />
            </div>

            <div class="form-group">
                <label for="Kennel" class="control-label">Kennel</label>
                <input name="kennel" class="form-control" placeholder=@Model.Dog.KennelID />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}